//AUTH
//LOGIN
export const LOGIN = 'LOGIN'
//REGISTER
export const REGISTER = 'REGISTER'

//COMICS
//GET SLIDES
export const GET_SLIDE = 'GET_SLIDE'
//GET ALL COMICS
export const GET_ALL_COMIC = 'GET_ALL_COMIC'
// //EDIT ROOMS
// export const EDIT_ROOMS = 'EDIT_ROOMS'
// //DELETE ROOMS
// export const DELETE_ROOMS = 'DELETE_ROOMS'

// FAVORITE
// GET FAVORITE
export const GET_FAVORITE = 'GET_FAVORITE'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'
// export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
// export const UPLOAD_IMAGE_CUSTOMER = 'UPLOAD_IMAGE_CUSTOMER'
// export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'

//EPISODE
//GET EPISODE
export const GET_EPISODE = 'GET_EPISODE'
// export const ADD_CHECKIN = 'ADD_CHECKIN'
// export const CHECKOUT = 'CHECKOUT'

// DETAIL EPISODE
//GET DETAIL EPISODE
export const GET_DETAIL_EPISODE = 'GET_DETAIL_EPISODE'
// export const ADD_CHECKIN = 'ADD_CHECKIN'
// export const CHECKOUT = 'CHECKOUT'

//CREATION
//GET CREATION
export const GET_CREATION = 'GET_CREATION'